import FWCore.ParameterSet.Config as cms

hiFJRhoAnalyzer = cms.EDAnalyzer(
    'HiFJRhoAnalyzer',
    etaMap        = cms.InputTag('hiFJRhoProducer','mapEtaEdges','HiForest'),
    rho           = cms.InputTag('hiFJRhoProducer','mapToRho'),
    rhom          = cms.InputTag('hiFJRhoProducer','mapToRhoM'),
    rhoCorr       = cms.InputTag('hiFJGridEmptyAreaCalculator','mapToRhoCorr'),
    rhomCorr      = cms.InputTag('hiFJGridEmptyAreaCalculator','mapToRhoMCorr'),
    rhoCorr1Bin   = cms.InputTag('hiFJGridEmptyAreaCalculator','mapToRhoCorr1Bin'),
    rhomCorr1Bin  = cms.InputTag('hiFJGridEmptyAreaCalculator','mapToRhoMCorr1Bin'),
    rhoGrid       = cms.InputTag('hiFJGridEmptyAreaCalculator','mapRhoVsEtaGrid'),
    meanRhoGrid   = cms.InputTag('hiFJGridEmptyAreaCalculator','mapMeanRhoVsEtaGrid'),
    etaMaxRhoGrid = cms.InputTag('hiFJGridEmptyAreaCalculator','mapEtaMaxGrid'),
    etaMinRhoGrid = cms.InputTag('hiFJGridEmptyAreaCalculator','mapEtaMinGrid'),
    ptJets        = cms.InputTag('hiFJRhoProducer','ptJets'),
    etaJets       = cms.InputTag('hiFJRhoProducer','etaJets'),
    areaJets      = cms.InputTag('hiFJRhoProducer','areaJets'),
    useModulatedRho = cms.bool(False),
)

hiFJRhoAnalyzerFinerBins = cms.EDAnalyzer(
    'HiFJRhoAnalyzer',
    etaMap        = cms.InputTag('hiFJRhoProducerFinerBins','mapEtaEdges','HiForest'),
    rho           = cms.InputTag('hiFJRhoProducerFinerBins','mapToRho'),
    rhom          = cms.InputTag('hiFJRhoProducerFinerBins','mapToRhoM'),
    rhoCorr       = cms.InputTag('hiFJGridEmptyAreaCalculatorFinerBins','mapToRhoCorr'),
    rhomCorr      = cms.InputTag('hiFJGridEmptyAreaCalculatorFinerBins','mapToRhoMCorr'),
    rhoCorr1Bin   = cms.InputTag('hiFJGridEmptyAreaCalculatorFinerBins','mapToRhoCorr1Bin'),
    rhomCorr1Bin  = cms.InputTag('hiFJGridEmptyAreaCalculatorFinerBins','mapToRhoMCorr1Bin'),
    rhoGrid       = cms.InputTag('hiFJGridEmptyAreaCalculatorFinerBins','mapRhoVsEtaGrid'),
    meanRhoGrid   = cms.InputTag('hiFJGridEmptyAreaCalculatorFinerBins','mapMeanRhoVsEtaGrid'),
    etaMaxRhoGrid = cms.InputTag('hiFJGridEmptyAreaCalculatorFinerBins','mapEtaMaxGrid'),
    etaMinRhoGrid = cms.InputTag('hiFJGridEmptyAreaCalculatorFinerBins','mapEtaMinGrid'),
    ptJets        = cms.InputTag('hiFJRhoProducerFinerBins','ptJets'),
    etaJets       = cms.InputTag('hiFJRhoProducerFinerBins','etaJets'),
    areaJets      = cms.InputTag('hiFJRhoProducerFinerBins','areaJets'),
    useModulatedRho = cms.bool(False),
)

hiPuRhoAnalyzer = hiFJRhoAnalyzer.clone(
    rho = cms.InputTag('hiPuRhoProducer','mapToRho'),
    etaMap = cms.InputTag('hiPuRhoProducer','mapEtaEdges','HiForest'),
    
    rhoExtra = cms.InputTag('hiPuRhoProducer','mapToRhoExtra'),
    rhom = cms.InputTag('hiPuRhoProducer','mapToRhoM'),
    rhoCorr = cms.InputTag('hiPuRhoProducer','mapToRhoMedian'),
    rhomCorr = cms.InputTag('hiPuRhoProducer','mapToRhoM'),
    rhoCorr1Bin = cms.InputTag('hiPuRhoProducer','mapToRho'),
    rhomCorr1Bin = cms.InputTag('hiPuRhoProducer','mapToRhoM'),
    nTow = cms.InputTag('hiPuRhoProducer','mapToNTow'),
    towExcludePt = cms.InputTag('hiPuRhoProducer','mapToTowExcludePt'),
    towExcludePhi = cms.InputTag('hiPuRhoProducer','mapToTowExcludePhi'),
    towExcludeEta = cms.InputTag('hiPuRhoProducer','mapToTowExcludeEta'),
    rhoGrid = cms.InputTag('hiFJGridEmptyAreaCalculator','mapRhoVsEtaGrid'),
    meanRhoGrid = cms.InputTag('hiFJGridEmptyAreaCalculator','mapMeanRhoVsEtaGrid'),
    etaMaxRhoGrid = cms.InputTag('hiFJGridEmptyAreaCalculator','mapEtaMaxGrid'),
    etaMinRhoGrid = cms.InputTag('hiFJGridEmptyAreaCalculator','mapEtaMinGrid'),
    rhoFlowFitParams = cms.InputTag('hiFJRhoFlowModulationProducer','rhoFlowFitParams'),
    ptJets = cms.InputTag('hiPuRhoProducer', 'ptJets'),
    etaJets = cms.InputTag('hiPuRhoProducer', 'etaJets'),
    areaJets = cms.InputTag('hiPuRhoProducer', 'areaJets'),
    useModulatedRho = cms.bool(True),
)